const data = {
   "nodes":[
      {
         "index":0,
         "name":"node-0"
      },
      {
         "index":1,
         "name":"node-1"
      },
      {
         "index":2,
         "name":"node-2"
      },
      {
         "index":3,
         "name":"node-3"
      },
      {
         "index":4,
         "name":"node-4"
      },
      {
         "index":5,
         "name":"node-5"
      },
      {
         "index":6,
         "name":"node-6"
      },
      {
         "index":7,
         "name":"node-7"
      },
      {
         "index":8,
         "name":"node-8"
      },
      {
         "index":9,
         "name":"node-9"
      },
      {
         "index":10,
         "name":"node-10"
      },
      {
         "index":11,
         "name":"node-0"
      },
      {
         "index":12,
         "name":"node-1"
      },
      {
         "index":13,
         "name":"node-2"
      },
      {
         "index":14,
         "name":"node-3"
      },
      {
         "index":15,
         "name":"node-4"
      },
      {
         "index":16,
         "name":"node-5"
      },
      {
         "index":17,
         "name":"node-6"
      },
      {
         "index":18,
         "name":"node-7"
      },
      {
         "index":19,
         "name":"node-8"
      },
      {
         "index":20,
         "name":"node-9"
      },
      {
         "index":21,
         "name":"node-0"
      },
      {
         "index":22,
         "name":"node-1"
      },
      {
         "index":23,
         "name":"node-2"
      },
      {
         "index":24,
         "name":"node-3"
      },
      {
         "index":25,
         "name":"node-4"
      },
      {
         "index":26,
         "name":"node-5"
      },
      {
         "index":27,
         "name":"node-6"
      },
      {
         "index":28,
         "name":"node-7"
      },
      {
         "index":29,
         "name":"node-8"
      },
      {
         "index":30,
         "name":"node-9"
      },
      {
         "index":31,
         "name":"node-0"
      },
      {
         "index":32,
         "name":"node-1"
      },
      {
         "index":33,
         "name":"node-2"
      },
      {
         "index":34,
         "name":"node-3"
      },
      {
         "index":35,
         "name":"node-4"
      },
      {
         "index":36,
         "name":"node-5"
      },
      {
         "index":37,
         "name":"node-6"
      },
      {
         "index":38,
         "name":"node-7"
      },
      {
         "index":39,
         "name":"node-8"
      },
      {
         "index":40,
         "name":"node-9"
      },
      {
         "index":41,
         "name":"node-0"
      },
      {
         "index":42,
         "name":"node-1"
      },
      {
         "index":43,
         "name":"node-2"
      },
      {
         "index":44,
         "name":"node-3"
      },
      {
         "index":45,
         "name":"node-4"
      },
      {
         "index":46,
         "name":"node-5"
      },
      {
         "index":47,
         "name":"node-6"
      },
      {
         "index":48,
         "name":"node-7"
      },
      {
         "index":49,
         "name":"node-8"
      },
      {
         "index":50,
         "name":"node-9"
      },
      {
         "index":51,
         "name":"node-10"
      },
      {
         "index":52,
         "name":"node-0"
      },
      {
         "index":53,
         "name":"node-1"
      },
      {
         "index":54,
         "name":"node-2"
      },
      {
         "index":55,
         "name":"node-3"
      },
      {
         "index":56,
         "name":"node-4"
      },
      {
         "index":57,
         "name":"node-5"
      },
      {
         "index":58,
         "name":"node-6"
      },
      {
         "index":59,
         "name":"node-7"
      },
      {
         "index":60,
         "name":"node-8"
      },
      {
         "index":61,
         "name":"node-9"
      },
      {
         "index":62,
         "name":"node-0"
      },
      {
         "index":63,
         "name":"node-1"
      },
      {
         "index":64,
         "name":"node-2"
      },
      {
         "index":65,
         "name":"node-3"
      },
      {
         "index":66,
         "name":"node-4"
      },
      {
         "index":67,
         "name":"node-5"
      },
      {
         "index":68,
         "name":"node-6"
      },
      {
         "index":69,
         "name":"node-7"
      },
      {
         "index":70,
         "name":"node-8"
      },
      {
         "index":71,
         "name":"node-9"
      },
      {
         "index":72,
         "name":"node-10"
      },
      {
         "index":73,
         "name":"node-11"
      },
      {
         "index":74,
         "name":"node-0"
      },
      {
         "index":75,
         "name":"node-1"
      },
      {
         "index":76,
         "name":"node-2"
      },
      {
         "index":77,
         "name":"node-3"
      },
      {
         "index":78,
         "name":"node-4"
      },
      {
         "index":79,
         "name":"node-5"
      },
      {
         "index":80,
         "name":"node-6"
      },
      {
         "index":81,
         "name":"node-7"
      },
      {
         "index":82,
         "name":"node-8"
      },
      {
         "index":83,
         "name":"node-9"
      },
      {
         "index":84,
         "name":"node-10"
      },
      {
         "index":85,
         "name":"node-11"
      },
      {
         "index":86,
         "name":"node-0"
      },
      {
         "index":87,
         "name":"node-1"
      },
      {
         "index":88,
         "name":"node-2"
      },
      {
         "index":89,
         "name":"node-3"
      },
      {
         "index":90,
         "name":"node-4"
      },
      {
         "index":91,
         "name":"node-5"
      },
      {
         "index":92,
         "name":"node-6"
      },
      {
         "index":93,
         "name":"node-7"
      },
      {
         "index":94,
         "name":"node-8"
      },
      {
         "index":95,
         "name":"node-9"
      }
   ],
   "links":[
      {
         "name":"link-1",
         "source":0,
         "target":1
      },
      {
         "name":"link-2",
         "source":0,
         "target":2
      },
      {
         "name":"link-3",
         "source":0,
         "target":3
      },
      {
         "name":"link-4",
         "source":0,
         "target":4
      },
      {
         "name":"link-5",
         "source":0,
         "target":5
      },
      {
         "name":"link-6",
         "source":0,
         "target":6
      },
      {
         "name":"link-7",
         "source":0,
         "target":7
      },
      {
         "name":"link-8",
         "source":0,
         "target":8
      },
      {
         "name":"link-9",
         "source":0,
         "target":9
      },
      {
         "name":"link-10",
         "source":0,
         "target":10
      },
      {
         "name":"link-0",
         "source":0,
         "target":0
      },
      {
         "name":"link-12",
         "source":11,
         "target":12
      },
      {
         "name":"link-13",
         "source":11,
         "target":13
      },
      {
         "name":"link-14",
         "source":11,
         "target":14
      },
      {
         "name":"link-15",
         "source":11,
         "target":15
      },
      {
         "name":"link-16",
         "source":11,
         "target":16
      },
      {
         "name":"link-17",
         "source":11,
         "target":17
      },
      {
         "name":"link-18",
         "source":11,
         "target":18
      },
      {
         "name":"link-19",
         "source":11,
         "target":19
      },
      {
         "name":"link-20",
         "source":11,
         "target":20
      },
      {
         "name":"link-11",
         "source":0,
         "target":11
      },
      {
         "name":"link-22",
         "source":21,
         "target":22
      },
      {
         "name":"link-23",
         "source":21,
         "target":23
      },
      {
         "name":"link-24",
         "source":21,
         "target":24
      },
      {
         "name":"link-25",
         "source":21,
         "target":25
      },
      {
         "name":"link-26",
         "source":21,
         "target":26
      },
      {
         "name":"link-27",
         "source":21,
         "target":27
      },
      {
         "name":"link-28",
         "source":21,
         "target":28
      },
      {
         "name":"link-29",
         "source":21,
         "target":29
      },
      {
         "name":"link-30",
         "source":21,
         "target":30
      },
      {
         "name":"link-21",
         "source":0,
         "target":21
      },
      {
         "name":"link-32",
         "source":31,
         "target":32
      },
      {
         "name":"link-33",
         "source":31,
         "target":33
      },
      {
         "name":"link-34",
         "source":31,
         "target":34
      },
      {
         "name":"link-35",
         "source":31,
         "target":35
      },
      {
         "name":"link-36",
         "source":31,
         "target":36
      },
      {
         "name":"link-37",
         "source":31,
         "target":37
      },
      {
         "name":"link-38",
         "source":31,
         "target":38
      },
      {
         "name":"link-39",
         "source":31,
         "target":39
      },
      {
         "name":"link-40",
         "source":31,
         "target":40
      },
      {
         "name":"link-31",
         "source":0,
         "target":31
      },
      {
         "name":"link-42",
         "source":41,
         "target":42
      },
      {
         "name":"link-43",
         "source":41,
         "target":43
      },
      {
         "name":"link-44",
         "source":41,
         "target":44
      },
      {
         "name":"link-45",
         "source":41,
         "target":45
      },
      {
         "name":"link-46",
         "source":41,
         "target":46
      },
      {
         "name":"link-47",
         "source":41,
         "target":47
      },
      {
         "name":"link-48",
         "source":41,
         "target":48
      },
      {
         "name":"link-49",
         "source":41,
         "target":49
      },
      {
         "name":"link-50",
         "source":41,
         "target":50
      },
      {
         "name":"link-51",
         "source":41,
         "target":51
      },
      {
         "name":"link-41",
         "source":0,
         "target":41
      },
      {
         "name":"link-53",
         "source":52,
         "target":53
      },
      {
         "name":"link-54",
         "source":52,
         "target":54
      },
      {
         "name":"link-55",
         "source":52,
         "target":55
      },
      {
         "name":"link-56",
         "source":52,
         "target":56
      },
      {
         "name":"link-57",
         "source":52,
         "target":57
      },
      {
         "name":"link-58",
         "source":52,
         "target":58
      },
      {
         "name":"link-59",
         "source":52,
         "target":59
      },
      {
         "name":"link-60",
         "source":52,
         "target":60
      },
      {
         "name":"link-61",
         "source":52,
         "target":61
      },
      {
         "name":"link-52",
         "source":0,
         "target":52
      },
      {
         "name":"link-63",
         "source":62,
         "target":63
      },
      {
         "name":"link-64",
         "source":62,
         "target":64
      },
      {
         "name":"link-65",
         "source":62,
         "target":65
      },
      {
         "name":"link-66",
         "source":62,
         "target":66
      },
      {
         "name":"link-67",
         "source":62,
         "target":67
      },
      {
         "name":"link-68",
         "source":62,
         "target":68
      },
      {
         "name":"link-69",
         "source":62,
         "target":69
      },
      {
         "name":"link-70",
         "source":62,
         "target":70
      },
      {
         "name":"link-71",
         "source":62,
         "target":71
      },
      {
         "name":"link-72",
         "source":62,
         "target":72
      },
      {
         "name":"link-73",
         "source":62,
         "target":73
      },
      {
         "name":"link-62",
         "source":0,
         "target":62
      },
      {
         "name":"link-75",
         "source":74,
         "target":75
      },
      {
         "name":"link-76",
         "source":74,
         "target":76
      },
      {
         "name":"link-77",
         "source":74,
         "target":77
      },
      {
         "name":"link-78",
         "source":74,
         "target":78
      },
      {
         "name":"link-79",
         "source":74,
         "target":79
      },
      {
         "name":"link-80",
         "source":74,
         "target":80
      },
      {
         "name":"link-81",
         "source":74,
         "target":81
      },
      {
         "name":"link-82",
         "source":74,
         "target":82
      },
      {
         "name":"link-83",
         "source":74,
         "target":83
      },
      {
         "name":"link-84",
         "source":74,
         "target":84
      },
      {
         "name":"link-85",
         "source":74,
         "target":85
      },
      {
         "name":"link-74",
         "source":0,
         "target":74
      },
      {
         "name":"link-87",
         "source":86,
         "target":87
      },
      {
         "name":"link-88",
         "source":86,
         "target":88
      },
      {
         "name":"link-89",
         "source":86,
         "target":89
      },
      {
         "name":"link-90",
         "source":86,
         "target":90
      },
      {
         "name":"link-91",
         "source":86,
         "target":91
      },
      {
         "name":"link-92",
         "source":86,
         "target":92
      },
      {
         "name":"link-93",
         "source":86,
         "target":93
      },
      {
         "name":"link-94",
         "source":86,
         "target":94
      },
      {
         "name":"link-95",
         "source":86,
         "target":95
      },
      {
         "name":"link-86",
         "source":0,
         "target":86
      }
   ]
};

export default data;
